FROM nginx:alpine

# install nginx source code to re-compile with modules
RUN wget "http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz" -O nginx.tar.gz && \
    apk add --no-cache --virtual .build-deps \
    gcc \
    libc-dev \
    make \
    openssl-dev \
    pcre-dev \
    zlib-dev \
    linux-headers \
    curl \
    gnupg \
    libxslt-dev \
    gd-dev \
    geoip-dev \
    libxml2-dev \
    libxml2-utils \
    perl-module-build \
    perl-dev \
    perl \
    nginx-mod-http-perl

RUN CONFARGS=$(nginx -V 2>&1 | sed -n -e 's/^.*arguments: //p') \
    mkdir -p /usr/src && \
    tar -zxC /usr/src -f nginx.tar.gz && \
    cd /usr/src/nginx-$NGINX_VERSION && \
    ./configure --with-http_perl_module=dynamic --with-compat $CONFARGS && \
    make && make install && rm -f nginx.tar.gz

# -Dusemultiplicity=yes -Dusethreads=yes -Dusemymalloc=no
# /usr/lib/perl5/core_perl/CORE
# --with-http_perl_module

WORKDIR / 
COPY /custom_node_nginx.conf /etc/nginx/conf.d/custom_node_nginx.conf
RUN echo -e "load_module modules/ngx_http_perl_module.so;\n" >> /etc/nginx/nginx.conf

EXPOSE 80:80
EXPOSE 443:443

RUN rm -f /etc/nginx/conf.d/default.conf
