FROM nginx:alpine

WORKDIR /
 
COPY /node_nginx.conf /etc/nginx/conf.d/custom_node_nginx.conf
COPY /nginx.conf /etc/nginx/nginx.conf


EXPOSE 80:80
EXPOSE 443:443

RUN rm -f /etc/nginx/conf.d/default.conf
